[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bincode = "1.3.3"
borsh = "1.5.5"
borsh-derive = "1.5.5"
cursor = "2.3.0"
rand = "0.9.0"
serde = "1.0.218"
solana-client = "2.2.0"
solana-sdk = "2.2.1"
solana-transaction-status = "2.2.0"
