[package]
name = "zk"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2 = { version = "1.0.2" }
anyhow = { version = "1.0.40", default-features = false }
plonky2_field = "1.0.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
bincode = "1.3.3"

